Repository MovingBlocks/TerasologyLauncher, pull requests merged in 2019-11, with the labels that each got.

#452 Provides updated PackageManager architecture
  src/main/java/org/terasology/launcher/LauncherConfiguration.java
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/NullLauncherConfiguration.java
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/game/GameDownloader.java
  src/main/java/org/terasology/launcher/game/GameStarter.java
  src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/java/org/terasology/launcher/packages/CustomRepositoryHandler.java
  src/main/java/org/terasology/launcher/packages/JenkinsHandler.java
  src/main/java/org/terasology/launcher/packages/Package.java
  src/main/java/org/terasology/launcher/packages/PackageDatabase.java
  src/main/java/org/terasology/launcher/packages/PackageManager.java
  src/main/java/org/terasology/launcher/packages/RepositoryHandler.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
  src/main/java/org/terasology/launcher/updater/SelfUpdater.java
  src/main/java/org/terasology/launcher/util/DirectoryCreator.java
  src/main/java/org/terasology/launcher/util/FileUtils.java
  src/main/java/org/terasology/launcher/util/GuiUtils.java
  src/main/java/org/terasology/launcher/util/LauncherDirectoryUtils.java
  src/main/java/org/terasology/launcher/util/LauncherManagedDirectory.java
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle.properties
  src/main/resources/org/terasology/launcher/packages/sources.json
  src/main/resources/org/terasology/launcher/views/application.fxml
  src/test/java/org/terasology/launcher/util/TestFileUtils.java
  src/test/java/org/terasology/launcher/util/TestLauncherDirectoryUtils.java
Labels: GSoC 2019

#472 Logging TextArea instead of TableView
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/LogViewController.java
  src/main/java/org/terasology/launcher/log/LogViewAppender.java
  src/main/resources/org/terasology/launcher/views/application.fxml
  src/main/resources/org/terasology/launcher/views/log-view.fxml
Labels: Topic: UI, Type: Enhancement

#475 Extract About tab controller
  build.gradle
  src/main/java/org/terasology/launcher/gui/javafx/AboutViewController.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/resources/org/terasology/launcher/views/about-view.fxml
  src/main/resources/org/terasology/launcher/views/application.fxml
Labels: Topic: UI, Type: Maintenance

#480 Refactor AboutViewController
  src/main/java/org/terasology/launcher/gui/javafx/AboutViewController.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
Labels: Topic: UI, Type: Maintenance

#476 Remove duplicate game (type and version) selection
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/resources/org/terasology/launcher/views/settings.fxml
Labels: Topic: UI, Type: Maintenance

#478 Extract Footer from main application controller
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/FXUtils.java
  src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
  src/main/java/org/terasology/launcher/gui/javafx/Warning.java
  src/main/resources/org/terasology/launcher/views/application.fxml
  src/main/resources/org/terasology/launcher/views/footer.fxml
Labels: Topic: UI, Type: Maintenance

#477 Extract ChangelogView from main application controller
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/ChangelogViewController.java
  src/main/resources/org/terasology/launcher/views/application.fxml
  src/main/resources/org/terasology/launcher/views/changelog-view.fxml
  src/main/resources/org/terasology/launcher/views/settings.fxml
Labels: Topic: UI, Type: Maintenance

#482 Enable Github actions
  .github/workflows/gradle.yml
Labels: Status: WIP, Topic: Tests/QA, Type: Enhancement

#483 Fix Checkstyle errors
  config/checkstyle/suppressions.xml
  src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
  src/main/java/org/terasology/launcher/gui/javafx/AboutViewController.java
  src/main/java/org/terasology/launcher/gui/javafx/ChangelogViewController.java
  src/main/java/org/terasology/launcher/gui/javafx/FXUtils.java
  src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
  src/main/java/org/terasology/launcher/gui/javafx/LogViewController.java
  src/main/java/org/terasology/launcher/gui/javafx/Warning.java
  src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
  src/main/java/org/terasology/launcher/util/DownloadUtils.java
  src/main/java/org/terasology/launcher/util/FileUtils.java
  src/main/java/org/terasology/launcher/util/LauncherDirectoryUtils.java
  src/main/java/org/terasology/launcher/util/LauncherManagedDirectory.java
  src/test/java/org/terasology/launcher/game/TestGameVersions.java
Labels: Topic: Tests/QA, Type: Maintenance

#484 Shows changelog of selected game package
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/ChangelogViewController.java
  src/main/java/org/terasology/launcher/packages/JenkinsHandler.java
  src/main/java/org/terasology/launcher/packages/Package.java
Labels: Topic: UI
