Repository MovingBlocks/TerasologyLauncher, pull requests merged in 2020-10, with the labels that each got.

#583 build: update JDK 11.0.7 >>> 11.0.8 and fix download task
  config/gradle/jre.gradle
Labels: Status: Actionable, Topic: CI/CD

#585 chore: replace custom LogLevel by slf4j.event.Level
  src/main/java/org/terasology/launcher/config/ConfigManager.java
  src/main/java/org/terasology/launcher/config/GameConfig.java
  src/main/java/org/terasology/launcher/game/GameStarter.java
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/java/org/terasology/launcher/settings/AbstractLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/util/LogLevel.java
  src/test/java/org/terasology/launcher/settings/TestBaseLauncherSettings.java
Labels: Status: Actionable, Type: Maintenance

#587 chore[build]: add TestFX dependency
  .github/workflows/push-validation.yml
  build.gradle
Labels: Topic: CI/CD, Topic: Tests/QA

#588 build: check in IDEA configuration (incl. updated copyright headers)
  .gitignore
  .idea/.gitignore
  .idea/checkstyle-idea.xml
  .idea/copyright/Terasology_Foundation.xml
  .idea/copyright/profiles_settings.xml
  .idea/misc.xml
  .idea/vcs.xml
Labels: Status: Actionable, Type: Maintenance

#586 chore: organize GuiUtils and FXUtils into Effects and Dialogs
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/Dialogs.java
  src/main/java/org/terasology/launcher/gui/javafx/Effects.java
  src/main/java/org/terasology/launcher/gui/javafx/FXUtils.java
  src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
Labels: Status: Actionable, Type: Maintenance

#591 ci: improve workflow
  .github/workflows/push-validation.yml
  build.gradle
  src/main/java/org/terasology/launcher/gui/javafx/Effects.java
Labels: Topic: CI/CD, Type: Maintenance

#571 Game Runner thread / subprocess improvements
  .idea/compiler.xml
  build.gradle
  src/main/java/org/terasology/launcher/game/GameRunner.java
  src/main/java/org/terasology/launcher/game/GameService.java
  src/main/java/org/terasology/launcher/game/GameStarter.java
  src/main/java/org/terasology/launcher/game/RunGameTask.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/FxTimer.java
  src/main/java/org/terasology/launcher/gui/javafx/LogViewController.java
  src/main/resources/org/terasology/launcher/views/application.fxml
  src/test/java/org/terasology/launcher/Matchers.java
  src/test/java/org/terasology/launcher/SlowTest.java
  src/test/java/org/terasology/launcher/StringIteratorInputStream.java
  src/test/java/org/terasology/launcher/game/MockProcesses.java
  src/test/java/org/terasology/launcher/game/TestGameRunner.java
  src/test/java/org/terasology/launcher/game/TestGameStarter.java
  src/test/java/org/terasology/launcher/game/TestRunGameTask.java
  src/test/java/org/terasology/launcher/game/UnixProcesses.java
  src/test/java/org/terasology/launcher/util/TestFileUtils.java
Labels: Topic: Documentation, Type: Enhancement

#592 ci: upload test report as build artifact
  .github/workflows/push-validation.yml
Labels: Topic: CI/CD

#590 refactoring: Streamline LauncherSettings to ease replacement
  src/main/java/org/terasology/launcher/LauncherConfiguration.java
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/NullLauncherConfiguration.java
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/LauncherSettings.java
  src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java
  src/main/java/org/terasology/launcher/settings/Settings.java
  src/main/java/org/terasology/launcher/settings/SettingsValidationRule.java
  src/test/java/org/terasology/launcher/settings/TestLauncherSettings.java
Labels: Status: WIP, Topic: Configuration, Type: Maintenance

#599 fix: remove doubled files when bundling the JRE
  config/gradle/jre.gradle
Labels: Topic: CI/CD, Type: Bug

#598 test: Fix Windows tests
  .gitignore
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  src/test/java/org/terasology/launcher/util/TestFileUtils.java
Labels: Topic: Tests/QA, Type: Bug

#574 fix: Download button tooltip error fixed
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
Labels: Type: Bug

#603 chore: Remove dead code (config package)
  src/main/java/org/terasology/launcher/config/Config.java
  src/main/java/org/terasology/launcher/config/ConfigManager.java
  src/main/java/org/terasology/launcher/config/ConfigReader.java
  src/main/java/org/terasology/launcher/config/ConfigValidator.java
  src/main/java/org/terasology/launcher/config/ConfigWriter.java
  src/main/java/org/terasology/launcher/config/GameConfig.java
  src/main/java/org/terasology/launcher/config/PackageAdapter.java
  src/main/java/org/terasology/launcher/config/PathAdapter.java
Labels: Type: Maintenance

#601 chore(idea): don't delegate compilation to gradle by default
  .idea/dictionaries/kevint.xml
  .idea/misc.xml
  .idea/runConfigurations/Test_All.xml
  build.gradle
Labels: Topic: CI/CD

#604 chore: remove deprecations on LauncherConfig and LauncherSettings
  src/main/java/org/terasology/launcher/LauncherConfiguration.java
  src/main/java/org/terasology/launcher/NullLauncherConfiguration.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/LauncherSettings.java
Labels: Type: Maintenance

#605 chore: remove self updater
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/NullLauncherConfiguration.java
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/LauncherSettings.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
  src/main/java/org/terasology/launcher/updater/SelfUpdater.java
  src/main/resources/org/terasology/launcher/views/settings.fxml
  src/test/java/org/terasology/launcher/settings/TestLauncherSettings.java
Labels: Type: Maintenance

#606 build(ci): enable check-run-reporter for push validation
  .github/workflows/push-validation.yml
Labels: Topic: CI/CD, Topic: Tests/QA
