Repository MovingBlocks/TerasologyLauncher, pull requests merged in 2020-05, with the labels that each got.

#556 test: Migrate to Junit5 (Jupiter)
  build.gradle
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/game/GameJob.java
  src/main/java/org/terasology/launcher/game/JobItem.java
  src/main/java/org/terasology/launcher/game/TerasologyGameVersion.java
  src/main/java/org/terasology/launcher/game/TerasologyGameVersionInfo.java
  src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
  src/main/java/org/terasology/launcher/game/VersionItem.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/ChangelogViewController.java
  src/main/java/org/terasology/launcher/util/DownloadUtils.java
  src/test/java/org/terasology/launcher/TestingUtils.java
  src/test/java/org/terasology/launcher/game/TestGameRunner.java
  src/test/java/org/terasology/launcher/game/TestGameVersions.java
  src/test/java/org/terasology/launcher/settings/TestBaseLauncherSettings.java
  src/test/java/org/terasology/launcher/util/TestFileUtils.java
  src/test/java/org/terasology/launcher/util/TestFileUtilsNoMock.java
  src/test/java/org/terasology/launcher/util/TestLanguages.java
  src/test/java/org/terasology/launcher/util/TestLauncherDirectoryUtils.java
Labels: Topic: Tests/QA, Type: Maintenance

#558 fix: Bundle the JRE, not the JDK.
  config/gradle/jre.gradle
Labels: Type: Maintenance

#559 fix: Remove unitialized variable in LauncherUpdater
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
Labels: Type: Bug

#560 fix: Remove Java 8 JVM arguments from settings
  src/main/java/org/terasology/launcher/config/ConfigValidator.java
  src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java
Labels: Type: Bug

#564 chore: Remove usage of JNA to determine Windows path
  build.gradle
  src/main/java/org/terasology/launcher/util/LauncherDirectoryUtils.java
  src/main/java/org/terasology/launcher/util/windows/Ole32.java
  src/main/java/org/terasology/launcher/util/windows/SavedGamesPathFinder.java
  src/main/java/org/terasology/launcher/util/windows/Shell32.java
Labels: Type: Maintenance

#566 chore: Prepare for Java 14
  .github/workflows/asset-upload.yml
  .github/workflows/push-validation.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/org/terasology/launcher/util/FileUtils.java
Labels: Topic: CI/CD, Type: Maintenance

#568 chore(gradle): Update Gradle to 6.4
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: Topic: CI/CD, Type: Maintenance

#567 chore: Replace jcabi Github client by github-api
  build.gradle
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/github/GitHubClient.java
  src/main/java/org/terasology/launcher/github/GitHubRelease.java
  src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java
  src/main/java/org/terasology/launcher/tasks/DownloadTask.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
  src/main/java/org/terasology/launcher/util/FileUtils.java
  src/main/java/org/terasology/launcher/util/LauncherDirectoryUtils.java
Labels: Type: Maintenance

#570 chore: Use new parser for markdown rendering
  build.gradle
  src/main/java/org/terasology/launcher/gui/javafx/AboutViewController.java
Labels: Type: Maintenance

#569 chore: Remove Swagger configuration
  build.gradle
  config/gradle/swagger.gradle
Labels: Topic: CI/CD, Type: Maintenance

#578 chore(gradle): upgrade to 6.4.1 from 6.4.0
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Topic: CI/CD, Type: Maintenance
