Repository MovingBlocks/TerasologyLauncher, pull requests merged in 2020-03, with the labels that each got.

#496 chore(actions): Add `release-drafter` action
  .github/release-drafter-config.yml
  .github/workflows/push-validation.yml
  .github/workflows/release-drafter.yml
Labels: Topic: CI/CD

#497 chore(actions): Build and upload assets on release
  .github/workflows/asset-upload.yml
  .github/workflows/release-draft.yml
Labels: Topic: CI/CD

#494 fix: launcher logo
  README.md
  src/main/resources/org/terasology/launcher/images/logo.png
Labels: Type: Bug

#500 fix(footer): Use java.awt.Desktop as fallback for HostServices
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
  src/main/java/org/terasology/launcher/util/HostServicesWrapper.java
Labels: Topic: UI, Type: Bug

#503 feat: cleanup and clarify settings
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_af.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_cs.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_de.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_en.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_es.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_fr.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_gl.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_hu.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_it.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_ja.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_lt.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_pl.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_pt.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_ru.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_tr.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_uk.properties
  src/main/resources/org/terasology/launcher/views/settings.fxml
Labels: Topic: UI, Type: Enhancement

#501 feat(packages): better names for game versions
  src/main/java/org/terasology/launcher/config/PackageAdapter.java
  src/main/java/org/terasology/launcher/game/GameStarter.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/packages/JenkinsHandler.java
  src/main/java/org/terasology/launcher/packages/Package.java
  src/main/java/org/terasology/launcher/packages/PackageDatabase.java
  src/main/java/org/terasology/launcher/packages/PackageManager.java
  src/main/resources/org/terasology/launcher/packages/sources.json
Labels: Topic: UI, Type: Enhancement

#502 fix: reset version box scroll bar when switching jobs
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
Labels: Topic: UI, Type: Bug

#509 chore(build): Clean up build files
  .github/workflows/asset-upload.yml
  build.gradle
  config/gradle/jre.gradle
Labels: Topic: CI/CD, Type: Maintenance

#511 fix(settings): typo in game arguments label
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_en.properties
Labels: Topic: UI, Type: Bug

#498 docs: move wiki into launcher repo
  CONTRIBUTING.md
  CREDITS.md
  README.md
  build.gradle
  docs/Add-New-Translation.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/images/200314_TerasologyLauncher_UI-settings.png
  docs/images/200314_TerasologyLauncher_UI.png
  docs/images/logo.png
  docs/images/logo.svg
  src/main/resources/org/terasology/launcher/images/forum.png
  src/main/resources/org/terasology/launcher/images/patreon.jpg
  src/main/resources/org/terasology/launcher/images/webchat.png
Labels: Topic: Documentation, Type: Enhancement

#512 feat: Infer version from Git
  .gitignore
  build.gradle
  src/template/VERSION.md
Labels: Type: Enhancement

#513 chore(gradle): remove IDE setup tasks
  README.md
  build.gradle
  config/gradle/environment.gradle
Labels: Status: Actionable, Topic: CI/CD, Type: Maintenance

#516 feat: Platform-specific distribution packages
  .gitignore
  build.gradle
  buildres/linux/TerasologyLauncher.run
  buildres/mac/Info.plist
  buildres/mac/Resources/terasology.icns
  buildres/windows32/TerasologyLauncher.x86.exe
  buildres/windows64/TerasologyLauncher.x64.exe
  bundles/linux/run_linux.sh
  bundles/macosx/MacOS/terasologylauncher.command
  config/gradle/bundles.gradle
  config/gradle/jre.gradle
  src/dist/TerasologyLauncher.exe
Labels: Status: Actionable, Type: Enhancement

#519 fix(action): restruce asset upload workflow and fix asset path
  .github/workflows/asset-upload.yml
Labels: Topic: CI/CD, Type: Bug

#518 fix: .gitattributes
  .gitattributes
Labels: Status: Actionable, Topic: CI/CD, Type: Bug

#523 fix(buildres): linux run script
  buildres/linux/TerasologyLauncher.run
Labels: Status: Actionable, Type: Bug

#527 chore: simplify FileUtils and fix "Unknown Windows"
  src/main/java/org/terasology/launcher/util/FileUtils.java
  src/main/java/org/terasology/launcher/util/OperatingSystem.java
Labels: Bite-size, Status: Actionable, Type: Maintenance

#524 chore(settings): clean up properties
  build.gradle
  src/main/java/org/terasology/launcher/game/GameSettings.java
  src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
  src/main/java/org/terasology/launcher/settings/AbstractLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/LauncherSettingsDecorator.java
  src/test/java/org/terasology/launcher/game/TestGameVersions.java
  src/test/java/org/terasology/launcher/settings/TestBaseLauncherSettings.java
Labels: Topic: Configuration, Type: Maintenance

#529 fix: remove HostServices (only working with Oracle JRE)
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
  src/main/java/org/terasology/launcher/util/HostServices.java
  src/main/java/org/terasology/launcher/util/HostServicesWrapper.java
Labels: Type: Maintenance

#531 feat: Show dialog for available updates (again)
  build.gradle
  config/gradle/jre.gradle
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/github/GitHubClient.java
  src/main/java/org/terasology/launcher/github/GitHubRelease.java
  src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
  src/main/java/org/terasology/launcher/updater/SelfUpdater.java
  src/main/java/org/terasology/launcher/version/TerasologyLauncherVersionInfo.java
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_cs.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_de.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_en.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_es.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_fr.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_gl.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_hu.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_it.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_ja.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_lt.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_pl.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_pt.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_ru.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_tr.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_uk.properties
  src/test/java/org/terasology/launcher/TestingUtils.java
  src/test/java/org/terasology/launcher/updater/TestLancherUpdater.java
Labels: Topic: UI, Type: Enhancement

#533 chore: Update Gradle to 6.2.2 and consume TeraConfig
  .gitignore
  build.gradle
  buildres/scripts/TerasologyLauncher.bat.patch
  buildres/scripts/TerasologyLauncher.patch
  config/checkstyle/checkstyle.xml
  config/gradle/jre.gradle
  config/gradle/quality.gradle
  config/pmd/pmd.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Topic: CI/CD, Type: Maintenance

#534 chore: Resovle Checkstyle warnings
  .github/workflows/push-validation.yml
  build.gradle
  config/checkstyle/suppressions.xml
  src/main/java/org/terasology/launcher/LauncherConfiguration.java
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/config/ConfigManager.java
  src/main/java/org/terasology/launcher/config/PackageAdapter.java
  src/main/java/org/terasology/launcher/game/TerasologyGameVersions.java
  src/main/java/org/terasology/launcher/github/GitHubClient.java
  src/main/java/org/terasology/launcher/github/GitHubRelease.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/settings/AbstractLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/util/HostServices.java
  src/main/java/org/terasology/launcher/util/windows/Ole32.java
  src/main/java/org/terasology/launcher/util/windows/Shell32.java
  src/test/java/org/terasology/launcher/game/TestGameVersions.java
  src/test/java/org/terasology/launcher/settings/TestBaseLauncherSettings.java
Labels: Status: Actionable, Type: Maintenance

#535 feat(usability): select last played or installed game
  src/main/java/org/terasology/launcher/config/Config.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/packages/PackageDatabase.java
  src/main/java/org/terasology/launcher/packages/PackageManager.java
  src/main/java/org/terasology/launcher/settings/AbstractLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
Labels: Status: Actionable, Topic: UI, Type: Enhancement

#537 fix: small adjustments in settings view
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_de.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_en.properties
  src/main/resources/org/terasology/launcher/views/settings.fxml
Labels: Status: Actionable, Topic: UI, Type: Bug

#536 feat: merge 'games' directory into launcher installation directory
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/packages/PackageManager.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
  src/main/java/org/terasology/launcher/util/FileUtils.java
  src/main/java/org/terasology/launcher/util/LauncherDirectoryUtils.java
  src/main/java/org/terasology/launcher/util/LauncherManagedDirectory.java
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_af.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_cs.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_de.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_en.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_es.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_fr.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_gl.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_hu.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_it.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_ja.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_lt.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_pl.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_pt.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_ru.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_tr.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_uk.properties
Labels: Status: Actionable, Topic: Configuration, Type: Maintenance

#538 fix: Remove (failing) CrashReporter
  build.gradle
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
Labels: Type: Bug
