Repository MovingBlocks/TerasologyLauncher, pull requests merged in 2020-11, with the labels that each got.

#608 fix(i18n): update Ukrainian locale strings
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_uk.properties
Labels: Topic: UI

#600 Game Runner improvements (take 2)
  .idea/runConfigurations/run.xml
  build.gradle
  src/main/java/org/terasology/launcher/game/GameRunner.java
  src/main/java/org/terasology/launcher/game/GameService.java
  src/main/java/org/terasology/launcher/game/GameStarter.java
  src/main/java/org/terasology/launcher/game/RunGameTask.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/FxTimer.java
  src/main/java/org/terasology/launcher/gui/javafx/LogViewController.java
  src/main/resources/org/terasology/launcher/views/application.fxml
  src/test/java/org/terasology/launcher/Matchers.java
  src/test/java/org/terasology/launcher/SlowTest.java
  src/test/java/org/terasology/launcher/StringIteratorInputStream.java
  src/test/java/org/terasology/launcher/game/MockProcesses.java
  src/test/java/org/terasology/launcher/game/TestGameRunner.java
  src/test/java/org/terasology/launcher/game/TestGameStarter.java
  src/test/java/org/terasology/launcher/game/TestRunGameTask.java
  src/test/java/org/terasology/launcher/game/UnixProcesses.java
  src/test/java/org/terasology/launcher/util/TestFileUtils.java
Labels: Topic: Documentation, Topic: Tests/QA, Type: Enhancement

#613 fix: various issues
  src/main/java/org/terasology/launcher/game/GameService.java
  src/main/java/org/terasology/launcher/game/GameStarter.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/LauncherSettings.java
Labels: Status: Actionable, Type: Bug

#612 epic: Rework package management and UI
  src/main/java/org/terasology/launcher/LauncherConfiguration.java
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/game/GameManager.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/ChangelogViewController.java
  src/main/java/org/terasology/launcher/gui/javafx/GameProfileCell.java
  src/main/java/org/terasology/launcher/gui/javafx/GameReleaseCell.java
  src/main/java/org/terasology/launcher/gui/javafx/PackageItem.java
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/java/org/terasology/launcher/gui/javafx/VersionItem.java
  src/main/java/org/terasology/launcher/model/Build.java
  src/main/java/org/terasology/launcher/model/GameIdentifier.java
  src/main/java/org/terasology/launcher/model/GameRelease.java
  src/main/java/org/terasology/launcher/model/Profile.java
  src/main/java/org/terasology/launcher/packages/CustomRepositoryHandler.java
  src/main/java/org/terasology/launcher/packages/JenkinsHandler.java
  src/main/java/org/terasology/launcher/packages/JenkinsRepository.java
  src/main/java/org/terasology/launcher/packages/LocalRepository.java
  src/main/java/org/terasology/launcher/packages/Package.java
  src/main/java/org/terasology/launcher/packages/PackageBuild.java
  src/main/java/org/terasology/launcher/packages/PackageDatabase.java
  src/main/java/org/terasology/launcher/packages/PackageManager.java
  src/main/java/org/terasology/launcher/packages/Repository.java
  src/main/java/org/terasology/launcher/packages/RepositoryHandler.java
  src/main/java/org/terasology/launcher/packages/db/DatabaseRepository.java
  src/main/java/org/terasology/launcher/packages/db/DatabaseRepositoryDeserializer.java
  src/main/java/org/terasology/launcher/packages/db/PackageMetadata.java
  src/main/java/org/terasology/launcher/repositories/Jenkins.java
  src/main/java/org/terasology/launcher/repositories/JenkinsRepositoryAdapter.java
  src/main/java/org/terasology/launcher/repositories/ReleaseRepository.java
  src/main/java/org/terasology/launcher/repositories/RepositoryManager.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/LauncherSettings.java
  src/main/java/org/terasology/launcher/tasks/DeleteTask.java
  src/main/java/org/terasology/launcher/tasks/DownloadTask.java
  src/main/resources/org/terasology/launcher/packages/schema.json
  src/main/resources/org/terasology/launcher/packages/sources.json
  src/main/resources/org/terasology/launcher/views/application.fxml
Labels: Topic: UI, Type: Maintenance

#614 fix(tests): fix flaky TestRunGameTask tests
  .idea/dictionaries/kevint.xml
  build.gradle
  src/test/java/org/terasology/launcher/game/TestRunGameTask.java
Labels: Topic: Tests/QA, Type: Bug

#615 chore(tests): remove extraneous waitForFxEvents calls
  src/test/java/org/terasology/launcher/game/TestRunGameTask.java
Labels: Topic: Tests/QA

#607 chore: fix check run annotations, use new codemetrics version
  build.gradle
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/settings/Settings.java
Labels: Status: WIP, Type: Maintenance

#617 chore: update license headers
  buildSrc/build.gradle
  buildSrc/src/main/groovy/org/terasology/gradlegoo/GooPlugin.groovy
  config/gradle/jre.gradle
  settings.gradle
  src/main/java/org/terasology/launcher/game/GameService.java
  src/main/java/org/terasology/launcher/game/GameStarter.java
  src/main/java/org/terasology/launcher/gui/javafx/AboutViewController.java
  src/main/java/org/terasology/launcher/gui/javafx/ChangelogViewController.java
  src/main/java/org/terasology/launcher/gui/javafx/Dialogs.java
  src/main/java/org/terasology/launcher/gui/javafx/Effects.java
  src/main/java/org/terasology/launcher/gui/javafx/FooterController.java
  src/main/java/org/terasology/launcher/gui/javafx/FxTimer.java
  src/main/java/org/terasology/launcher/gui/javafx/LogViewController.java
  src/main/java/org/terasology/launcher/gui/javafx/SettingsController.java
  src/main/java/org/terasology/launcher/gui/javafx/Warning.java
  src/main/java/org/terasology/launcher/log/TempLogFilePropertyDefiner.java
  src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java
  src/main/java/org/terasology/launcher/settings/Settings.java
  src/main/java/org/terasology/launcher/settings/SettingsValidationRule.java
  src/main/java/org/terasology/launcher/tasks/ProgressListener.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
  src/main/java/org/terasology/launcher/util/BundleUtils.java
  src/main/java/org/terasology/launcher/util/DirectoryCreator.java
  src/main/java/org/terasology/launcher/util/DownloadException.java
  src/main/java/org/terasology/launcher/util/DownloadUtils.java
  src/main/java/org/terasology/launcher/util/FileUtils.java
  src/main/java/org/terasology/launcher/util/GameDataDirectoryNames.java
  src/main/java/org/terasology/launcher/util/HostServices.java
  src/main/java/org/terasology/launcher/util/JavaHeapSize.java
  src/main/java/org/terasology/launcher/util/JobResult.java
  src/main/java/org/terasology/launcher/util/Languages.java
  src/main/java/org/terasology/launcher/util/LauncherDirectoryUtils.java
  src/main/java/org/terasology/launcher/util/LauncherManagedDirectory.java
  src/main/java/org/terasology/launcher/util/LauncherStartFailedException.java
  src/main/java/org/terasology/launcher/util/Platform.java
  src/main/java/org/terasology/launcher/util/visitor/ArchiveCopyVisitor.java
  src/main/java/org/terasology/launcher/util/visitor/DeleteFileVisitor.java
  src/main/java/org/terasology/launcher/util/visitor/LocalCopyVisitor.java
  src/main/java/org/terasology/launcher/version/TerasologyLauncherVersionInfo.java
  src/test/java/org/terasology/launcher/Matchers.java
  src/test/java/org/terasology/launcher/SlowTest.java
  src/test/java/org/terasology/launcher/StringIteratorInputStream.java
  src/test/java/org/terasology/launcher/game/MockProcesses.java
  src/test/java/org/terasology/launcher/game/TestGameStarter.java
  src/test/java/org/terasology/launcher/game/UnixProcesses.java
  src/test/java/org/terasology/launcher/settings/TestLauncherSettings.java
  src/test/java/org/terasology/launcher/util/TestLanguages.java
  src/test/java/org/terasology/launcher/util/TestLauncherDirectoryUtils.java
Labels: Status: Actionable, Topic: Documentation, Type: Maintenance

#618 build: update Gradle (6.4.1 >>> 6.7.1)
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Status: Actionable, Type: Maintenance

#619 epic: continue launcher clean-up
  build.gradle
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/game/RunGameTask.java
  src/main/java/org/terasology/launcher/model/LauncherVersion.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/LauncherSettings.java
  src/main/java/org/terasology/launcher/ui/AboutViewController.java
  src/main/java/org/terasology/launcher/ui/ApplicationController.java
  src/main/java/org/terasology/launcher/ui/ChangelogViewController.java
  src/main/java/org/terasology/launcher/ui/Dialogs.java
  src/main/java/org/terasology/launcher/ui/Effects.java
  src/main/java/org/terasology/launcher/ui/FooterController.java
  src/main/java/org/terasology/launcher/ui/FxTimer.java
  src/main/java/org/terasology/launcher/ui/GameProfileCell.java
  src/main/java/org/terasology/launcher/ui/GameReleaseCell.java
  src/main/java/org/terasology/launcher/ui/LogViewController.java
  src/main/java/org/terasology/launcher/ui/SettingsController.java
  src/main/java/org/terasology/launcher/ui/Warning.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
  src/main/java/org/terasology/launcher/version/TerasologyLauncherVersionInfo.java
  src/main/resources/org/terasology/launcher/views/about-view.fxml
  src/main/resources/org/terasology/launcher/views/application.fxml
  src/main/resources/org/terasology/launcher/views/changelog-view.fxml
  src/main/resources/org/terasology/launcher/views/footer.fxml
  src/main/resources/org/terasology/launcher/views/log-view.fxml
  src/main/resources/org/terasology/launcher/views/settings.fxml
Labels: Type: Maintenance
