Repository MovingBlocks/TerasologyLauncher, pull requests merged in 2020-04, with the labels that each got.

#540 chore: Extract private inner classes from ApplicationController
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/game/GameDownloader.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/GameDownloadWorker.java
  src/main/java/org/terasology/launcher/gui/javafx/PackageItem.java
  src/main/java/org/terasology/launcher/gui/javafx/VersionItem.java
  src/main/java/org/terasology/launcher/packages/PackageManager.java
  src/main/java/org/terasology/launcher/tasks/DeleteTask.java
  src/main/java/org/terasology/launcher/tasks/DownloadTask.java
  src/main/java/org/terasology/launcher/tasks/ProgressListener.java
  src/main/java/org/terasology/launcher/util/DownloadUtils.java
  src/main/java/org/terasology/launcher/util/DummyProgressListener.java
Labels: Status: Actionable, Type: Maintenance

#543 feat: replace `OperatingSystem` enum with `Platform` object
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/config/ConfigManager.java
  src/main/java/org/terasology/launcher/util/LauncherDirectoryUtils.java
  src/main/java/org/terasology/launcher/util/OperatingSystem.java
  src/main/java/org/terasology/launcher/util/Platform.java
  src/test/java/org/terasology/launcher/util/TestLauncherDirectoryUtils.java
Labels: Status: Actionable, Type: Enhancement

#553 fix(action): Trigger push-validation for PRs
  .github/workflows/push-validation.yml
Labels: Topic: CI/CD

#552 fix: Don't block the application thread on message dialog
  src/main/java/org/terasology/launcher/util/GuiUtils.java
Labels: Type: Bug

#548 feat: Upgrade to Java 11
  .github/workflows/asset-upload.yml
  .github/workflows/push-validation.yml
  build.gradle
  config/gradle/jre.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/config/ConfigManager.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/packages/PackageDatabase.java
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/test/java/org/terasology/launcher/TestingUtils.java
  src/test/java/org/terasology/launcher/game/TestGameRunner.java
  src/test/java/org/terasology/launcher/game/TestGameVersions.java
  src/test/java/org/terasology/launcher/util/TestFileUtils.java
  src/test/java/org/terasology/launcher/util/TestFileUtilsNoMock.java
  src/test/java/org/terasology/launcher/util/TestLauncherDirectoryUtils.java
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: Type: Enhancement

#555 chore: remove unused GameDownloader
  src/main/java/org/terasology/launcher/game/GameDownloader.java
  src/main/java/org/terasology/launcher/gui/javafx/ApplicationController.java
  src/main/java/org/terasology/launcher/gui/javafx/GameDownloadWorker.java
Labels: Type: Maintenance
