Repository MovingBlocks/TerasologyLauncher, pull requests merged in 2021-08, with the labels that each got.

#654 fix(GameStarter): do not depend on GameRelease to know the engine version
  src/main/java/org/terasology/launcher/game/GameManager.java
  src/main/java/org/terasology/launcher/game/GameService.java
  src/main/java/org/terasology/launcher/game/GameStarter.java
  src/main/java/org/terasology/launcher/game/Installation.java
  src/main/java/org/terasology/launcher/game/VersionHistory.java
  src/main/java/org/terasology/launcher/model/GameIdentifier.java
  src/main/java/org/terasology/launcher/model/GameRelease.java
  src/main/java/org/terasology/launcher/ui/ApplicationController.java
  src/main/resources/org/terasology/launcher/bundle/MessageBundle.properties
  src/main/resources/org/terasology/launcher/bundle/MessageBundle_en.properties
  src/test/java/org/terasology/launcher/game/StubInstallation.java
  src/test/java/org/terasology/launcher/game/TestGameStarter.java
Labels: Type: Bug, Type: Enhancement

#645 chore: update to jdk 11.0.12 from 11.0.8
  config/gradle/jre.gradle
Labels: Type: Maintenance

#657 fix(LauncherSettings): do not send a zero-length argument
  src/main/java/org/terasology/launcher/settings/LauncherSettings.java
Labels: Type: Bug, Blocker

#638 feat: resolve Terasology.jar either from 'libs' or 'lib'
  src/main/java/org/terasology/launcher/game/GameStarter.java
  src/main/java/org/terasology/launcher/game/Installation.java
  src/test/java/org/terasology/launcher/game/StubInstallation.java
  src/test/java/org/terasology/launcher/game/TestGameStarter.java
Labels: Type: Enhancement

#658 feat: hide pre-releases by default
  src/main/java/org/terasology/launcher/settings/BaseLauncherSettings.java
  src/main/java/org/terasology/launcher/settings/LauncherSettings.java
  src/main/java/org/terasology/launcher/ui/ApplicationController.java
  src/main/java/org/terasology/launcher/ui/SettingsController.java
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_de.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_en.properties
  src/main/resources/org/terasology/launcher/views/settings.fxml
Labels: Type: Enhancement, Topic: UI

#659 fix: pass JVM heap settings in correct order to GameStarter
  src/main/java/org/terasology/launcher/game/GameService.java
Labels: Type: Bug
