Repository MovingBlocks/TerasologyLauncher, pull requests merged in 2021-12, with the labels that each got.

#666 refactor: change API of Settings#load/store to use folder path
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/settings/Settings.java
  src/main/java/org/terasology/launcher/ui/ApplicationController.java
  src/main/java/org/terasology/launcher/ui/SettingsController.java
  src/test/java/org/terasology/launcher/settings/TestLauncherSettings.java
Labels: Topic: Documentation, Type: Maintenance, Topic: Configuration

#670 feat(i18n): Update Ukrainian language strings & fill in missing i18n
  src/main/java/org/terasology/launcher/ui/ApplicationController.java
  src/main/java/org/terasology/launcher/ui/SettingsController.java
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_en.properties
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_uk.properties
  src/main/resources/org/terasology/launcher/views/application.fxml
  src/main/resources/org/terasology/launcher/views/settings.fxml
Labels: Type: Enhancement, Topic: UI

#667 feat: 1:1 migration from LauncherSettings >>> Settings
  src/main/java/org/terasology/launcher/LauncherConfiguration.java
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/game/GameService.java
  src/main/java/org/terasology/launcher/settings/LauncherSettingsValidator.java
  src/main/java/org/terasology/launcher/settings/Settings.java
  src/main/java/org/terasology/launcher/settings/SettingsValidationRule.java
  src/main/java/org/terasology/launcher/ui/ApplicationController.java
  src/main/java/org/terasology/launcher/ui/SettingsController.java
  src/main/java/org/terasology/launcher/util/Languages.java
  src/test/java/org/terasology/launcher/settings/TestLauncherSettings.java
Labels: Type: Enhancement, Topic: Configuration
