Repository MovingBlocks/TerasologyLauncher, pull requests merged in 2022-11, with the labels that each got.

#681 i18n: reduce log spam for missing labels
  src/main/java/org/terasology/launcher/util/I18N.java
Labels: Type: Enhancement, Topic: UI

#682 feat: add missing german translations
  src/main/resources/org/terasology/launcher/bundle/LabelsBundle_de.properties
Labels: Type: Enhancement, Status: Actionable

#679 i18n: use properties and bindings for i18n of resources bundles
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/TerasologyLauncher.java
  src/main/java/org/terasology/launcher/settings/LauncherSettings.java
  src/main/java/org/terasology/launcher/settings/Settings.java
  src/main/java/org/terasology/launcher/ui/AboutViewController.java
  src/main/java/org/terasology/launcher/ui/ApplicationController.java
  src/main/java/org/terasology/launcher/ui/ChangelogViewController.java
  src/main/java/org/terasology/launcher/ui/Dialogs.java
  src/main/java/org/terasology/launcher/ui/FooterController.java
  src/main/java/org/terasology/launcher/ui/GameReleaseCell.java
  src/main/java/org/terasology/launcher/ui/SettingsController.java
  src/main/java/org/terasology/launcher/updater/LauncherUpdater.java
  src/main/java/org/terasology/launcher/util/BundleUtils.java
  src/main/java/org/terasology/launcher/util/I18N.java
  src/main/java/org/terasology/launcher/util/JavaHeapSize.java
  src/main/java/org/terasology/launcher/util/Languages.java
  src/test/java/org/terasology/launcher/settings/TestLauncherSettings.java
  src/test/java/org/terasology/launcher/util/TestI18N.java
  src/test/java/org/terasology/launcher/util/TestLanguages.java
Labels: Type: Bug, Type: Enhancement, Topic: UI

#683 doc: udpate documentation
  README.md
  docs/i18n.md
  docs/release.md
Labels: Topic: Documentation, Status: Actionable

#684 feat: remove game profile selection (fixed on OMEGA)
  src/main/java/org/terasology/launcher/LauncherInitTask.java
  src/main/java/org/terasology/launcher/game/GameManager.java
  src/main/java/org/terasology/launcher/repositories/RepositoryManager.java
  src/main/java/org/terasology/launcher/ui/ApplicationController.java
  src/main/java/org/terasology/launcher/ui/FooterController.java
  src/main/java/org/terasology/launcher/util/I18N.java
  src/main/resources/org/terasology/launcher/views/application.fxml
Labels: Type: Enhancement, Topic: UI, Status: Actionable, Type: Maintenance

#685 chore: update Gradle (7.1.1 >>> 7.5.1) and dependencies
  build.gradle
  buildscript-gradle.lockfile
  gradle.lockfile
  gradle/wrapper/gradle-wrapper.properties
Labels: Status: Actionable, Type: Maintenance, Topic: CI/CD

#688 test: add test to ensure that all supported languages have language flag icons
  src/test/java/org/terasology/launcher/util/ResourceTests.java
Labels: Topic: Tests/QA
